### ISSUE TITLE
还是比较粗疏的更新。。。。

### ISSUE THREAD

**Issue by 02030pllolipop** [gera2ld/stylish-mx#11]
1. 啥设定也没有
2. 旧版数据梅拉(╬ﾟ◥益◤ﾟ)，手动导入数据中，没自动的呀。。。。。。
3. 看红框懂意思不解析

![default](https://user-images.githubusercontent.com/7941949/34098773-6e3a67d2-e418-11e7-97c2-69ded91d5d1a.png)

**Comment by gera2ld** [comment]
哈哈，慢慢来，先保证主要功能可用

**Comment by gera2ld** [comment]
旧版数据并没有丢，我这几天做个导入旧版数据的功能

**Comment by gera2ld** [comment]
3.0.1应该有自动导入旧数据的功能，有问题吗？
下个版本恢复导入和导出。

**Comment by 02030pllolipop** [comment]
@gera2ld 啥设定也没有：自动更新和自动刷新页面等等

**Comment by 02030pllolipop** [comment]
@gera2ld 加载css的效能比旧版低了许多，
是不是以前写的规则要更新，还是插件的问题？？？

**Comment by gera2ld** [comment]
@kliop00023 傲游有点问题：http://bbs.maxthon.cn/forum.php?mod=viewthread&tid=18869&extra=page%3D1  会莫名其妙地卡几秒。旧版没用这个技术，我再看看有没有办法绕过这个bug。。

**Comment by 02030pllolipop** [comment]
@gera2ld 唉唉唉你直接去以下问吧：
http://www.maxthon.com/mx/bug/post/
http://bbs.maxthon.cn/forum-69-1.html
自行问开发组的Q……

**Comment by gera2ld** [comment]
他们开发已经跟我联系了，傲游就是有这个bug。

**Comment by gera2ld** [comment]
下个版本（3.0.3）将恢复到2.x的加载速度，这个issue可以关了吧
