### ISSUE TITLE
新版不兼容旧版的规则写法

### ISSUE THREAD

**Issue by 02030pllolipop** [gera2ld/stylish-mx#12]
我是不会的，只是看结果而言。。。
反正以下的例子在最近的更新运行不了，
出个FAQs吧。。。。。。

1. `a:visited{color: #adad19!important;}
a:hover {
    text-decoration: underline;
}`
2. 看帖：stylish插件更新至3.0.1，还是无效。。。 - M5问题反馈 - 傲游社区
http://bbs.maxthon.cn/thread-18730-1-1.html

**Comment by gera2ld** [comment]
规则是空吗？

**Comment by 02030pllolipop** [comment]
@gera2ld 
![default](https://user-images.githubusercontent.com/7941949/34155858-e8c57cca-e4f5-11e7-88a5-a74688af4fcf.png)

**Comment by 02030pllolipop** [comment]
fixed: be27593
