### ISSUE TITLE
YouTube下的页面无法分开配对

### ISSUE THREAD

**Issue by 02030pllolipop** [gera2ld/stylish-mx#13]
看
YouTube下的match rule没效 · Issue #100 · violentmonkey/violentmonkey-mx
https://github.com/violentmonkey/violentmonkey-mx/issues/100

**Comment by gera2ld** [comment]
stylish目前不支持单页应用

**Comment by 02030pllolipop** [comment]
@gera2ld 那可以支持么/咋用脚本实现？？？

**Comment by gera2ld** [comment]
脚本实现可以研究一下劫持 history API。
如果在stylish里实现的话，原理同上，会影响浏览器原生方法，污染全局环境了，感觉不太好。。。所以暂不考虑实现。

**Comment by 02030pllolipop** [comment]
@gera2ld Σ(lliдﾟﾉ)ﾉ 外星文听不懂哦……(((ﾟДﾟ;)))
